import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";

import React from "react";
import { cn } from "../lib/utils";
import { Header } from "./components/Header";
import { Providers } from "@/providers";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen min-w-screen  bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <Providers>
          <Header />
          <main className="container mx-auto px-2">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
